---
title: "IndividualSubFams"
author: "April Wright"
date: "2022-09-28"
output: html_document
---

```{r}
Rhinopomatidae = c("Rhinopoma_hardwickii", "Rhinopoma_muscatellum", "Rhinopoma_macinnesi", "Rhinopoma_microphyllum", "Rhinopoma_hadramauticum")

# No var? Craseonycteridae = c("Craseonycteris_thonglongyai" )

# No var? Megadermatidae = c("Lavia_frons", "Megaderma_spasma", "Megaderma_lyra", "Megaderma_lyra","Eudiscoderma_thongareeae")

Rhinolophidae = c("Rhinolophus_hillorum", "Rhinolophus_madurensis", "Rhinolophus_landeri", "Rhinolophus_alcyone", "Rhinolophus_hipposideros", "Rhinolophus_swinnyi", "Rhinolophus_capensis", "Rhinolophus_simulator", "Rhinolophus_denti", "Rhinolophus_rufus", "Rhinolophus_blasii", "Rhinolophus_xinanzhongguoensis", "Rhinolophus_clivosus", "Rhinolophus_ferrumequinum", "Rhinolophus_eloquens", "Rhinolophus_mossambicus", "Rhinolophus_huananus", "Rhinolophus_fumigatus", "Rhinolophus_hilli", "Rhinolophus_hildebrandtii", "Rhinolophus_mabuensis", "Rhinolophus_cohenae", "Rhinolophus_smithersi", "Rhinolophus_canuti", "Rhinolophus_subbadius", "Rhinolophus_darlingi", "Rhinolophus_convexus", "Rhinolophus_ruwenzorii", "Rhinolophus_maclaudi", "Rhinolophus_mehelyi", "Rhinolophus_euryale", "Rhinolophus_yunanensis", "Rhinolophus_pearsonii", "Rhinolophus_euryotis", "Rhinolophus_arcuatus", "Rhinolophus_creaghi", "Rhinolophus_kahuzi", "Rhinolophus_subrufus", "Rhinolophus_coelophyllus", "Rhinolophus_shameli", "Rhinolophus_bocharicus", "Rhinolophus_stheno", "Rhinolophus_affinis", "Rhinolophus_sinicus", "Rhinolophus_thomasi", "Rhinolophus_rouxii", "Rhinolophus_acuminatus", "Rhinolophus_inops", "Rhinolophus_nereis", "Rhinolophus_malayanus", "Rhinolophus_luctoides", "Rhinolophus_chaseni", "Rhinolophus_paradoxolophus", "Rhinolophus_marshalli", "Rhinolophus_osgoodi", "Rhinolophus_mitratus", "Rhinolophus_adami", "Rhinolophus_macrotis", "Rhinolophus_siamensis", "Rhinolophus_shortridgei", "Rhinolophus_rex", "Rhinolophus_celebensis", "Rhinolophus_sakejiensis", "Rhinolophus_virgo", "Rhinolophus_philippinensis", "Rhinolophus_keyensis", "Rhinolophus_megaphyllus", "Rhinolophus_robinsoni", "Rhinolophus_borneensis", "Rhinolophus_thailandensis", "Rhinolophus_cognatus", "Rhinolophus_schnitzleri", "Rhinolophus_maendeleo", "Rhinolophus_lepidus", "Rhinolophus_pusillus", "Rhinolophus_montanus", "Rhinolophus_guineensis", "Rhinolophus_formosae", "Rhinolophus_trifoliatus", "Rhinolophus_sedulus", "Rhinolophus_deckenii", "Rhinolophus_ziama", "Rhinolophus_willardi", "Rhinolophus_luctus", "Rhinolophus_silvestris", "Rhinolophus_francisi", "Rhinolophus_beddomei")

Hipposideridae = c("Aselliscus_tricuspidatus", "Aselliscus_stoliczkanus", "Asellia_arabica", "Asellia_tridens", "Asellia_patrizii", "Paracoelops_megalotis", "Coelops_frithii", "Coelops_hirsutus", "Coelops_robinsoni", "Triaenops_afer", "Triaenops_rufus", "Triaenops_parvus", "Triaenops_persicus", "Triaenops_menamena", "Hipposideros_nequam", "Hipposideros_calcaratus", "Hipposideros_camerunensis", "Hipposideros_caffer", "Hipposideros_wollastoni", "Hipposideros_abae", "Hipposideros_beatus", "Hipposideros_lamottei", "Hipposideros_ruber", "Hipposideros_fuliginosus", "Hipposideros_doriae", "Hipposideros_dyacorum", "Hipposideros_fulvus", "Hipposideros_halophyllus", "Hipposideros_muscinus", "Hipposideros_macrobullatus", "Hipposideros_ater", "Hipposideros_ridleyi", "Hipposideros_cineraceus", "Hipposideros_speoris", "Hipposideros_khaokhouayensis", "Hipposideros_megalotis", "Hipposideros_rotalis", "Hipposideros_pomona", "Hipposideros_bicolor", "Hipposideros_sorenseni", "Hipposideros_cervinus", "Hipposideros_galeritus", "Hipposideros_pygmaeus", "Hipposideros_orbiculus", "Hipposideros_papua", "Hipposideros_coxi", "Hipposideros_curtus", "Hipposideros_jonesi", "Hipposideros_breviceps", "Hipposideros_marisae", "Hipposideros_boeadii", "Hipposideros_semoni", "Hipposideros_stenotis", "Hipposideros_alongensis", "Hipposideros_lekaguli", "Hipposideros_turpis", "Hipposideros_maggietaylorae", "Hipposideros_pratti", "Hipposideros_scutinares", "Hipposideros_lylei", "Hipposideros_corynophyllus", "Hipposideros_dinops", "Hipposideros_pelingensis", "Hipposideros_thomensis", "Hipposideros_demissus", "Hipposideros_diadema", "Hipposideros_lankadiva", "Hipposideros_edwardshilli", "Hipposideros_durgadasi", "Hipposideros_larvatus", "Hipposideros_hypophyllus", "Hipposideros_grandis", "Hipposideros_griffini", "Hipposideros_pendelburyi", "Hipposideros_armiger", "Hipposideros_coronatus", "Hipposideros_madurae", "Hipposideros_obscurus", "Hipposideros_inexpectatus", "Anthops_ornatus", "Hipposideros_einnaythu", "Hipposideros_sumbae", "Hipposideros_cyclops", "Hipposideros_crumeniferus", "Hipposideros_vittatus", "Hipposideros_gigas", "Hipposideros_inornatus", "Hipposideros_commersoni")

Rhinonycteridae = c("Cloeotis_percivali", "Rhinonicteris_aurantia", "Paratriaenops_pauliani", "Paratriaenops_auritus", "Paratriaenops_furculus")

Pteropodidae <- c("Syconycteris_australis", "Syconycteris_hobbit","Syconycteris_carolinae", "Macroglossus_sobrinus", "Macroglossus_minimus", "Harpyionycteris_whiteheadi", "Harpyionycteris_celebensis", "Rousettus_bidens", "Dobsonia_chapmani", "Dobsonia_moluccensis", "Dobsonia_emersa", "Dobsonia_inermis", "Dobsonia_praedatrix", "Dobsonia_anderseni", "Dobsonia_minor", "Dobsonia_exoleta", "Dobsonia_peronii", "Dobsonia_viridis", "Dobsonia_pannietensis", "Dobsonia_beauforti", "Dobsonia_crenulata", "Nyctimene_draconilla", "Nyctimene_certans", "Nyctimene_robinsoni", "Nyctimene_cephalotes", "Nyctimene_masalai", "Nyctimene_albiventer", "Nyctimene_keasti", "Nyctimene_vizcaccia", "Nyctimene_minutus", "Nyctimene_cyclotis", "Nyctimene_sanctacrucis", "Nyctimene_major", "Nyctimene_rabori", "Nyctimene_aello", "Nyctimene_malaitensis", "Paranyctimene_tenax", "Paranyctimene_raptor", "Eidolon_helvum", "Eidolon_dupreanum", "Pteralopex_anceps", "Pteralopex_pulchra", "Pteralopex_flanneryi", "Pteralopex_taki", "Pteralopex_atrata", "Mirimiri_acrodonta", "Rousettus_linduensis", "Desmalopex_microleucopterus", "Melonycteris_melanops", "Melonycteris_woodfordi", "Melonycteris_fardoulisi", "Styloctenium_wallacei", "Styloctenium_mindorensis", "Pteropus_capistratus", "Pteropus_howensis", "Pteropus_aruensis", "Pteropus_samoensis", "Pteropus_rayneri", "Pteropus_anetianus", "Pteropus_faunulus", "Pteropus_tuberculatus", "Pteropus_nitendiensis", "Pteropus_intermedius", "Pteropus_temminckii", "Pteropus_fundatus", "Pteropus_keyensis", "Pteropus_ornatus", "Pteropus_personatus", "Pteropus_pohlei", "Pteropus_mariannus", "Pteropus_yapensis", "Pteropus_pelewensis", "Pteropus_loochoensis", "Pteropus_admiralitatum", "Pteropus_tonganus", "Pteropus_speciosus", "Pteropus_conspicillatus", "Pteropus_hypomelanus", "Pteropus_griseus", "Pteropus_alecto", "Pteropus_ualanus", "Pteropus_neohibernicus", "Pteropus_poliocephalus", "Pteropus_ocularis", "Pteropus_dasymallus", "Pteropus_melanopogon", "Pteropus_pumilus", "Pteropus_chrysoproctus", "Pteropus_rennelli", "Pteropus_brunneus", "Pteropus_vampyrus", "Pteropus_rodricensis", "Pteropus_giganteus", "Pteropus_lylei", "Pteropus_niger", "Pteropus_aldabrensis", "Pteropus_rufus", "Pteropus_seychellensis", "Pteropus_argentatus", "Pteropus_livingstonii", "Pteropus_pselaphon", "Pteropus_voeltzkowi", "Pteropus_scapulatus", "Pteropus_caniceps", "Pteropus_melanotus", "Pteropus_vetulus", "Pteropus_cognatus", "Pteropus_lombocensis", "Pteropus_tokudae", "Pteropus_molossinus", "Pteropus_pelagicus", "Pteropus_pilosus", "Pteropus_gilliardorum", "Pteropus_mahaganus", "Pteropus_woodfordi", "Pteropus_subniger", "Pteropus_macrotis", "Acerodon_mackloti", "Acerodon_celebensis", "Acerodon_leucotis", "Acerodon_jubatus", "Acerodon_humilis", "Casinycteris_ophiodon", "Casinycteris_campomaanensis", "Casinycteris_argynnis", "Scotonycteris_zenkeri", "Scotonycteris_occidentalis", "Scotonycteris_bergmansi", "Rousettus_amplexicaudatus", "Rousettus_spinalatus", "Rousettus_celebensis", "Rousettus_obliviosus", "Rousettus_madagascariensis", "Rousettus_leschenaultii", "Rousettus_aegyptiacus", "Megaloglossus_woermanni", "Megaloglossus_azagnyi", "Myonycteris_relicta", "Myonycteris_torquata", "Myonycteris_brachycephala", "Myonycteris_angolensis", "Hypsignathus_monstrosus", "Epomops_buettikoferi", "Epomops_dobsonii", "Epomops_franqueti", "Nanonycteris_veldkampii", "Epomophorus_crypturus", "Epomophorus_minimus", "Epomophorus_labiatus", "Epomophorus_anselli", "Epomophorus_grandis", "Micropteropus_pusillus", "Micropteropus_intermedius", "Epomophorus_angolensis", "Epomophorus_gambianus", "Epomophorus_wahlbergi", "Rousettus_lanosus", "Eonycteris_spelaea", "Eonycteris_robusta", "Eonycteris_major", "Thoopterus_suhaniahae", "Thoopterus_nigrescens", "Chironax_melanocephalus", "Aproteles_bulmerae", "Penthetor_lucasi", "Alionycteris_paucidentata", "Otopteropus_cartilagonodus", "Plerotes_anchietae", "Haplonycteris_fischeri", "Notopteris_neocaledonica", "Notopteris_macdonaldi", "Aethalops_alecto", "Aethalops_aequalis", "Balionycteris_maculata", "Sphaerias_blanfordi", "Latidens_salimalii", "Dyacopterus_spadiceus", "Dyacopterus_brooksi", "Dyacopterus_rickarti", "Ptenochirus_jagori", "Ptenochirus_minor", "Megaerops_wetmorei", "Megaerops_niphanae", "Megaerops_kusnotoi", "Megaerops_ecaudatus", "Cynopterus_luzoniensis", "Cynopterus_sphinx", "Cynopterus_brachyotis", "Cynopterus_nusatenggara", "Cynopterus_minutus", "Cynopterus_horsfieldii", "Cynopterus_titthaecheilus")

# NO VAR  Myzopodidae = c("Myzopoda_aurita", "Myzopoda_schliemanni")
# NO VAR Thyropteridae = c("Thyroptera_discifera", "Thyroptera_devivoi", "Thyroptera_lavali", "Thyroptera_wynneae", "Thyroptera_tricolor")
# NO VAR Noctilionidae = c("Noctilio_albiventris", "Noctilio_leporinus")
# NO VAR  Furipteridae = c("Furipterus_horrens", "Amorphochilus_schnablii")
Phyllostomidae = c("Diaemus_youngi", "Scleronycteris_ega", "Desmodus_draculae", "Desmodus_rotundus", "Diphylla_ecaudata", "Lampronycteris_brachyotis", "Micronycteris_hirsuta", "Micronycteris_matses", "Micronycteris_megalotis", "Micronycteris_microtis", "Micronycteris_buriri", "Micronycteris_giovanniae", "Micronycteris_brosseti", "Micronycteris_yatesi", "Micronycteris_sanborni", "Micronycteris_minuta", "Micronycteris_schmidtorum", "Lonchorhina_aurita", "Lonchorhina_orinocensis", "Phylloderma_stenops", "Mimon_crenulatum", "Phyllostomus_latifolius", "Phyllostomus_latifolius", "Phyllostomus_elongatus", "Phyllostomus_hastatus", "Tonatia_bidens", "Tonatia_saurophila", "Phyllostomus_discolor", "Lophostoma_brasiliense", "Lophostoma_carrikeri", "Lophostoma_kalkoae", "Lophostoma_yasuni", "Lophostoma_schulzi", "Lophostoma_silvicolum", "Lophostoma_aequatorialis", "Lophostoma_evotis", "Lonchorhina_inusitata", "Mimon_cozumelae", "Macrophyllum_macrophyllum", "Mimon_koepckeae", "Trachops_cirrhosus", "Mimon_bennettii", "Chrotopterus_auritus", "Vampyrum_spectrum", "Xeronycteris_vieirai", "Platalina_genovensium", "Lonchophylla_chocoana", "Lonchophylla_peracchii", "Lonchophylla_fornicata", "Lonchophylla_orcesi", "Lonchophylla_robusta", "Lonchophylla_orienticollina", "Lonchophylla_handleyi", "Lonchophylla_inexpectata", "Lonchophylla_dekeyseri", "Lonchophylla_bokermanni", "Lionycteris_spurrelli", "Lonchophylla_hesperia", "Lonchophylla_concava", "Lonchophylla_mordax", "Lonchophylla_thomasi","Lonchophylla_thomasi", "Hsunycteris_pattoni", "Hsunycteris_cadenai", "Hsunycteris_thomasi", "Trinycteris_nicefori", "Glyphonycteris_behnii", "Glyphonycteris_sylvestris", "Glyphonycteris_daviesi", "Carollia_perspicillata", "Carollia_brevicauda", "Carollia_sowelli", "Carollia_subrufa", "Carollia_manu", "Carollia_castanea", "Carollia_benkeithi", "Rhinophylla_alethina", "Rhinophylla_fischerae", "Rhinophylla_pumilio", "Ametrida_centurio", "Pygoderma_bilabiatum", "Centurio_senex", "Sphaeronycteris_toxophyllum", "Stenoderma_rufum","Stenoderma_rufum", "Phyllops_falcatus", "Ardops_nichollsi", "Ariteus_flavescens", "Ectophylla_alba", "Artibeus_hirsutus", "Artibeus_inopinatus", "Artibeus_jamaicensis", "Artibeus_lituratus", "Artibeus_obscurus", "Artibeus_amplus", "Artibeus_planirostris", "Artibeus_fimbriatus", "Artibeus_fraterculus", "Artibeus_concolor", "Dermanura_anderseni", "Dermanura_rava", "Dermanura_glaucus", "Dermanura_gnomus", "Dermanura_bogotensis", "Dermanura_cinereus", "Dermanura_toltecus", "Dermanura_phaeotis", "Dermanura_watsoni", "Dermanura_incomitatus", "Dermanura_rosenbergii", "Dermanura_aztecus", "Enchisthenes_hartii", "Vampyressa_bidens", "Vampyressa_elisabethae", "Vampyressa_brocki", "Vampyressa_nymphaea", "Vampyressa_sinchi", "Chiroderma_vizottoi", "Chiroderma_salvini", "Chiroderma_improvisum", "Chiroderma_villosum", "Chiroderma_doriae", "Chiroderma_trinitatum", "Vampyressa_thyone", "Vampyressa_pusilla", "Vampyressa_melissa", "Mesophylla_macconnelli", "Vampyrodes_caraccioli", "Platyrrhinus_recifinus", "Platyrrhinus_nitelinea", "Platyrrhinus_guianensis", "Platyrrhinus_angustirostris", "Platyrrhinus_fusciventris", "Platyrrhinus_matapalensis", "Platyrrhinus_helleri", "Platyrrhinus_umbratus", "Platyrrhinus_brachycephalus", "Platyrrhinus_nigellus", "Platyrrhinus_vittatus", "Platyrrhinus_albericoi", "Platyrrhinus_masu", "Platyrrhinus_ismaeli", "Platyrrhinus_dorsalis", "Platyrrhinus_infuscus", "Platyrrhinus_aurarius", "Platyrrhinus_lineatus", "Platyrrhinus_chocoensis","Uroderma_bilobatum", "Uroderma_bakeri", "Uroderma_magnirostrum", "Sturnira_paulsoni", "Sturnira_angeli", "Sturnira_luisi", "Sturnira_lilium", "Sturnira_bakeri", "Sturnira_parvidens", "Sturnira_erythromos", "Sturnira_mistratensis", "Sturnira_burtonlimi", "Sturnira_oporaphilum", "Sturnira_ludovici", "Sturnira_hondurensis", "Sturnira_tildae", "Sturnira_perla", "Sturnira_magna", "Sturnira_sorianoi", "Sturnira_bogotensis", "Sturnira_mordax", "Sturnira_koopmanhilli", "Sturnira_aratathomasi", "Sturnira_nana", "Sturnira_bidens", "Monophyllus_plethodon", "Monophyllus_redmani", "Glossophaga_morenoi", "Glossophaga_longirostris", "Glossophaga_leachii", "Glossophaga_commissarisi", "Glossophaga_soricina", "Leptonycteris_curasoae", "Leptonycteris_yerbabuenae", "Leptonycteris_nivalis", "Erophylla_bombifrons", "Erophylla_sezekorni", "Phyllonycteris_aphylla", "Phyllonycteris_poeyi", "Brachyphylla_cavernarum", "Brachyphylla_nana", "Hylonycteris_underwoodi", "Lonchorhina_marinkellei", "Lonchorhina_fernandezi", "Lichonycteris_obscura", "Choeronycteris_mexicana", "Choeroniscus_minor", "Choeroniscus_periosus", "Choeroniscus_godmani","Musonycteris_harrisoni", "Anoura_cultrata", "Anoura_caudifer", "Anoura_luismanueli", "Anoura_canishina", "Anoura_latidens", "Anoura_geoffroyi", "Anoura_fistulata", "Macrotus_californicus", "Macrotus_waterhousii", "Neonycteris_pusilla", "Dryadonycteris_capixaba")


#No var? Mormoopidae = c("Mormoops_blainvillei", "Mormoops_megalophylla", "Pteronotus_personatus", "Pteronotus_davyi", "Pteronotus_gymnonotus", "Pteronotus_quadridens", "Pteronotus_macleayii", "Pteronotus_paraguanensis", "Pteronotus_parnellii")
#No var? Mystracidae = c("Mystacina_robusta", "Mystacina_tuberculata") 
#No var? Nycteridae = c("Nycteris_madagascariensis", "Nycteris_macrotis", "Nycteris_gambiensis", "Nycteris_aurita", "Nycteris_arge", "Nycteris_javanica", "Nycteris_tragata", "Nycteris_woodi", "Nycteris_major", "Nycteris_grandis", "Nycteris_hispida", "Nycteris_thebaica", "Nycteris_parisii", "Nycteris_vinsoni", "Nycteris_nana", "Nycteris_intermedia")

Emballonuridae = c("Emballonura_serii", "Emballonura_beccarii", "Emballonura_dianae", "Emballonura_monticola", "Emballonura_alecto", "Emballonura_furax", "Emballonura_raffrayana", "Emballonura_semicaudata", "Emballonura_tiavato", "Emballonura_atrata", "Coleura_seychellensis", "Coleura_kibomalandy", "Coleura_afra", "Peropteryx_leucoptera", "Peropteryx_pallidoptera", "Peropteryx_trinitatis", "Peropteryx_macrotis", "Peropteryx_kappleri", "Cormura_brevirostris", "Cyttarops_alecto", "Mosia_nigrescens", "Diclidurus_isabellus", "Diclidurus_scutatus", "Diclidurus_ingens", "Diclidurus_albus", "Balantiopteryx_plicata", "Balantiopteryx_io", "Balantiopteryx_infusca", "Rhynchonycteris_naso", "Saccopteryx_gymnura", "Saccopteryx_canescens", "Saccopteryx_antioquensis", "Saccopteryx_bilineata", "Saccopteryx_leptura", "Centronycteris_maximiliani", "Centronycteris_centralis", "Saccolaimus_flaviventris", "Saccolaimus_mixtus", "Saccolaimus_peli", "Saccolaimus_saccolaimus", "Taphozous_hildegardeae", "Taphozous_melanopogon", "Taphozous_troughtoni", "Taphozous_perforatus", "Taphozous_georgianus", "Taphozous_theobaldi", "Taphozous_achates", "Taphozous_nudiventris", "Taphozous_hamiltoni", "Taphozous_mauritianus", "Taphozous_kapalgensis", "Taphozous_longimanus", "Taphozous_australis", "Taphozous_hilli")
# No var? Natalidae = c("Chilonatalus_tumidifrons", "Chilonatalus_micropus", "Nyctiellus_lepidus", "Natalus_mexicanus", "Natalus_espiritosantensis", "Natalus_saturatus", "Natalus_tumidirostris", "Natalus_stramineus", "Natalus_primus", "Natalus_jamaicensis", "Natalus_major", "Natalus_lanatus")

Molossidae = c("Tomopeas_ravus", "Myopterus_whitleyi", "Myopterus_daubentonii", "Platymops_setiger", "Mormopterus_francoismoutoui", "Mormopterus_jugularis", "Cheiromeles_torquatus", "Cheiromeles_parvidens", "Tadarida_insignis", "Molossus_barnesi", "Tadarida_teniotis", "Tadarida_lobata", "Tadarida_fulminans", "Tadarida_australis", "Mormopterus_phrudus", "Molossus_currentium", "Mormopterus_loriae", "Mormopterus_doriae", "Mormopterus_minutus", "Mormopterus_halli", "Mormopterus_planiceps", "Mormopterus_beccarii", "Mormopterus_lumsdenae", "Mormopterus_kitcheneri", "Tadarida_ventralis", "Mormopterus_eleryi", "Mormopterus_acetabulosus", "Mormopterus_norfolkensis", "Sauromys_petrophilus", "Tadarida_brasiliensis", "Otomops_wroughtoni", "Otomops_formosus", "Otomops_papuensis", "Otomops_martiensseni", "Otomops_johnstonei", "Otomops_madagascariensis", "Otomops_secundus", "Molossops_mattogrossensis", "Cynomops_abrasus", "Cynomops_greenhalli", "Cynomops_mexicanus", "Cynomops_paranus", "Cynomops_planirostris", "Molossops_aequatorianus", "Molossops_temminckii", "Molossops_neglectus", "Molossus_molossus", "Molossus_rufus", "Molossus_pretiosus", "Tadarida_latouchei", "Molossus_coibensis", "Promops_nasutus", "Promops_centralis", "Nyctinomops_macrotis", "Nyctinomops_aurispinosus", "Nyctinomops_kalinowskii", "Nyctinomops_laticaudatus", "Nyctinomops_femorosaccus", "Eumops_hansae", "Eumops_patagonicus", "Eumops_bonariensis", "Eumops_maurus", "Eumops_auripendulus", "Eumops_perotis", "Eumops_floridanus", "Eumops_chiribaya", "Eumops_ferox", "Eumops_glaucinus", "Eumops_wilsoni", "Eumops_trumbulli", "Eumops_dabbenei", "Eumops_underwoodi", "Molossus_sinaloae", "Tadarida_aegyptiaca", "Tadarida_kuboriensis", "Molossus_alvarezi", "Tadarida_jobimena", "Chaerephon_bemmeleni", "Chaerephon_tomensis", "Mops_spurrelli", "Mops_midas", "Mops_demonstrator", "Mops_petersoni", "Chaerephon_bregullae", "Mops_thersites", "Chaerephon_atsinanana", "Chaerephon_pumilus", "Chaerephon_chapini", "Mops_bakarii", "Chaerephon_bivittatus", "Mops_brachypterus", "Mops_trevori", "Chaerephon_major", "Chaerephon_gallagheri", "Mops_leucostigma", "Mops_condylurus", "Mops_niangarae", "Mops_niveiventer", "Chaerephon_aloysiisabaudiae", "Chaerephon_nigeriae", "Mops_sarasinorum", "Chaerephon_russatus", "Chaerephon_ansorgei", "Mops_congicus", "Chaerephon_jobensis", "Chaerephon_solomonis", "Mops_nanulus", "Chaerephon_plicatus", "Chaerephon_johorensis", "Mops_mops", "Molossus_aztecus")

#No var? Cistugidae <- c("Cistugo_seabrae", "Cistugo_lesueuri")

Vesper <- c("Scotorepens_balstoni", "Scotorepens_greyii", "Scotorepens_orion", "Scotorepens_sanborni", "Scotozous_dormeri", "Pharotis_imogene", "Scoteanax_rueppellii", "Mimetillus_moloneyi", "Nycticeius_cubanus", "Nycticeius_humeralis", "Nycticeius_aenobarbus", "Lasiurus_xanthinus", "Lasiurus_ega", "Lasiurus_castaneus", "Lasiurus_degelidus", "Lasiurus_insularis", "Lasiurus_intermedius", "Lasiurus_ebenus", "Lasiurus_borealis", "Lasiurus_pfeifferi", "Lasiurus_minor", "Lasiurus_atratus", "Lasiurus_blossevillii", "Lasiurus_seminolus", "Lasiurus_cinereus", "Lasiurus_varius", "Lasiurus_egregius", "Parastrellus_hesperus", "Otonycteris_hemprichii", "Pipistrellus_murrayi", "Rhogeessa_tumida", "Rhogeessa_aeneus", "Rhogeessa_bickhami", "Rhogeessa_io", "Rhogeessa_menchuae", "Rhogeessa_genowaysi", "Rhogeessa_minutilla", "Rhogeessa_parvula", "Rhogeessa_mira", "Rhogeessa_hussoni", "Rhogeessa_gracilis", "Rhogeessa_alleni", "Pipistrellus_inexspectatus", "Pipistrellus_kitcheneri", "Antrozous_pallidus", "Bauerus_dubiaquercus", "Barbastella_leucomelas", "Barbastella_beijingensis", "Barbastella_barbastellus", "Euderma_maculatum", "Pipistrellus_papuanus", "Plecotus_sardus", "Plecotus_sacrimontis", "Plecotus_macrobullaris", "Plecotus_auritus", "Plecotus_ognevi", "Plecotus_balensis", "Plecotus_christii", "Plecotus_austriacus", "Plecotus_teneriffae", "Plecotus_kolombatovici", "Plecotus_taivanus", "Idionycteris_phyllotis", "Corynorhinus_rafinesquii", "Corynorhinus_townsendii", "Corynorhinus_mexicanus", "Hesperoptenus_blanfordi", "Glauconycteris_poensis", "Glauconycteris_superba", "Glauconycteris_beatrix", "Pipistrellus_stenopterus", "Pipistrellus_coromandra", "Pipistrellus_tenuis", "Pipistrellus_paterculus", "Pipistrellus_javanicus", "Pipistrellus_minahassae", "Pipistrellus_abramus", "Pipistrellus_adamsi", "Arielulus_cuprosus", "Pipistrellus_ceylonicus", "Glischropus_bucephalus", "Glischropus_tylopus", "Glischropus_aquilus", "Glischropus_javanus", "Nyctalus_furvus", "Nyctalus_leisleri", "Nyctalus_azoreum", "Nyctalus_lasiopterus", "Nyctalus_aviator", "Nyctalus_noctula", "Nyctalus_plancyi", "Nyctalus_montanus", "Pipistrellus_pipistrellus", "Pipistrellus_hanaki", "Pipistrellus_pygmaeus", "Eptesicus_andinus", "Pipistrellus_angulatus", "Pipistrellus_hesperidus", "Pipistrellus_kuhlii", "Pipistrellus_deserti", "Pipistrellus_maderensis", "Pipistrellus_nathusii", "Pipistrellus_imbricatus", "Pipistrellus_sturdeei", "Pipistrellus_rueppellii", "Eptesicus_innoxius", "Scotoecus_albofuscus", "Scotoecus_hirundo", "Scotoecus_pallidus", "Vespertilio_sinensis", "Vespertilio_murinus", "Eptesicus_tatei", "Nycticeinops_schlieffeni", "Glauconycteris_machadoi", "Chalinolobus_dwyeri", "Pipistrellus_eisentrauti", "Pipistrellus_crassulus", "Eptesicus_floweri", "Pipistrellus_endoi", "Neoromicia_nana", "Neoromicia_roseveari", "Neoromicia_brunnea", "Neoromicia_helios", "Neoromicia_zuluensis", "Neoromicia_tenuipinnis", "Neoromicia_rendalli", "Hypsugo_dolichodon", "Hypsugo_lanzai", "Hypsugo_bemainty", "Hypsugo_anchietae", "Neoromicia_somalica", "Neoromicia_guineensis", "Neoromicia_melckorum", "Laephotis_botswanae", "Laephotis_angolensis", "Laephotis_namibensis", "Laephotis_wintoni", "Neoromicia_robertsi", "Neoromicia_malagasyensis", "Neoromicia_flavescens", "Neoromicia_matroka", "Neoromicia_capensis", "Pipistrellus_ariel", "Pipistrellus_cadornae", "Falsistrellus_mordax", "Falsistrellus_tasmaniensis", "Falsistrellus_petersi", "Falsistrellus_affinis", "Falsistrellus_mackenziei", "Glauconycteris_humeralis", "Pipistrellus_savii", "Pipistrellus_savii", "Eptesicus_guadeloupensis", "Pipistrellus_alaschanicus", "Nyctophilus_bifax", "Nyctophilus_sherrini", "Nyctophilus_arnhemensis", "Nyctophilus_nebulosus", "Nyctophilus_howensis", "Nyctophilus_walkeri", "Nyctophilus_microdon", "Nyctophilus_gouldi", "Nyctophilus_timoriensis", "Nyctophilus_geoffroyi", "Nyctophilus_corbeni", "Nyctophilus_shirleyae", "Nyctophilus_microtis", "Nyctophilus_heran", "Pipistrellus_joffrei", "Pipistrellus_pulveratus", "Glauconycteris_alboguttata", "Pipistrellus_nanulus", "Chalinolobus_neocaledonicus", "Pipistrellus_musciculus", "Chalinolobus_tuberculatus", "Pipistrellus_lophurus", "Chalinolobus_nigrogriseus", "Vespadelus_pumilus", "Vespadelus_douglasorum", "Vespadelus_baverstocki", "Vespadelus_caurinus", "Vespadelus_troughtoni", "Vespadelus_regulus", "Vespadelus_vulturnus", "Vespadelus_finlaysoni", "Vespadelus_darlingtoni", "Chalinolobus_morio", "Chalinolobus_gouldii", "Arielulus_torquatus", "Pipistrellus_macrotis", "Eptesicus_dimissus", "Glauconycteris_kenyacola", "Tylonycteris_robustula", "Tylonycteris_pygmaeus", "Tylonycteris_pachypus", "Philetor_brachypterus", "Hesperoptenus_tickelli", "Glauconycteris_gleni", "Pipistrellus_permixtus", "Arielulus_societatis", "Pipistrellus_rusticus", "Eptesicus_platyops", "Hesperoptenus_gaskelli", "Eptesicus_nasutus", "Pipistrellus_aero", "Eptesicus_fuscus", "Eptesicus_brasiliensis", "Eptesicus_pachyotis", "Eptesicus_furinalis", "Eptesicus_diminutus", "Pipistrellus_raceyi", "Eptesicus_chiriquinus", "Chalinolobus_picatus", "Histiotus_humboldti", "Histiotus_montanus", "Histiotus_magellanicus", "Histiotus_velatus", "Histiotus_alienus", "Histiotus_macrotus", "Histiotus_laephotis", "Eptesicus_hottentotus", "Eptesicus_serotinus", "Eptesicus_nilssonii", "Glauconycteris_curryae", "Eptesicus_kobayashii", "Eptesicus_gobiensis", "Eptesicus_bobrinskoi", "Hesperoptenus_doriae", "Eptesicus_pachyomus", "Eptesicus_bottae", "Eptesicus_isabellinus", "Ia_io", "Pipistrellus_westralis", "Scotomanes_ornatus", "Pipistrellus_vordermanni", "Eptesicus_japonensis", "Hesperoptenus_tomesi", "Lasionycteris_noctivagans", "Pipistrellus_anthonyi", "Arielulus_circumdatus", "Pipistrellus_arabicus", "Pipistrellus_collinus", "Arielulus_aureocollaris", "Eptesicus_lobatus", "Glauconycteris_variegata", "Pipistrellus_wattsi", "Glauconycteris_argentata", "Glauconycteris_egeria", "Scotophilus_kuhlii", "Scotophilus_nucella", "Scotophilus_nux", "Scotophilus_nigrita", "Scotophilus_robustus", "Scotophilus_dinganii", "Scotophilus_ejetai", "Scotophilus_trujilloi", "Scotophilus_collinus", "Scotophilus_andrewreborii", "Scotophilus_celebensis", "Scotophilus_borbonicus", "Scotophilus_livingstonii", "Scotophilus_tandrefana", "Scotophilus_marovaza", "Scotophilus_heathii", "Scotophilus_leucogaster", "Scotophilus_viridis", "Kerivoula_phalaena", "Kerivoula_krauensis", "Kerivoula_myrella", "Kerivoula_muscina", "Kerivoula_hardwickii", "Kerivoula_kachinensis", "Kerivoula_titania", "Kerivoula_argentata", "Kerivoula_africana", "Kerivoula_flora", "Kerivoula_whiteheadi", "Kerivoula_eriophora", "Kerivoula_minuta", "Kerivoula_intermedia", "Kerivoula_papillosa", "Kerivoula_lenis", "Kerivoula_agnella", "Kerivoula_cuprosa", "Kerivoula_lanosa", "Kerivoula_pellucida", "Kerivoula_smithii", "Kerivoula_picta", "Murina_tiensa", "Murina_harrisoni", "Murina_ryukyuana", "Murina_beelzebub", "Murina_ussuriensis", "Murina_balaensis", "Murina_fusca", "Murina_huttoni", "Murina_tenebrosa", "Murina_guilleni", "Murina_chrysochaetes", "Murina_harpioloides", "Murina_shuipuensis", "Murina_leucogaster", "Murina_puta", "Murina_bicolor", "Murina_hilgendorfi", "Murina_aurata", "Murina_eleryi", "Murina_gracilis", "Murina_recondita", "Murina_annamitica", "Murina_aenea", "Murina_walstoni", "Murina_florium", "Murina_suilla", "Murina_rozendaali", "Murina_cineracea", "Murina_tubinaris", "Murina_pluvialis", "Murina_jaintiana", "Murina_fionae", "Murina_cyclotis", "Murina_peninsularis", "Murina_loreliae", "Myotis_septentrionalis", "Myotis_diminutus", "Myotis_auriculus", "Myotis_leibii", "Myotis_californicus", "Myotis_melanorhinus", "Myotis_ciliolabrum", "Myotis_volans", "Myotis_bucharensis", "Myotis_sodalis", "Myotis_keenii", "Myotis_evotis", "Myotis_lucifugus", "Myotis_thysanodes", "Myotis_brandtii", "Myotis_cobanensis", "Myotis_fortidens", "Myotis_atacamensis", "Myotis_dominicensis", "Myotis_nesopolus", "Myotis_martiniquensis", "Myotis_vivesi", "Myotis_austroriparius", "Myotis_grisescens", "Myotis_badius", "Myotis_velifer", "Myotis_yumanensis", "Myotis_albescens", "Myotis_chiloensis", "Myotis_nigricans", "Myotis_oxyotus", "Myotis_levis", "Myotis_keaysi", "Myotis_planiceps", "Myotis_simus", "Myotis_riparius", "Myotis_elegans", "Myotis_aelleni", "Myotis_ruber", "Myotis_dinellii", "Myotis_peninsularis", "Myotis_moluccarum", "Myotis_australis", "Myotis_alcathoe", "Myotis_mystacinus", "Myotis_annectans", "Myotis_gomantongensis", "Myotis_montivagus", "Myotis_pruinosus", "Myotis_secundus", "Myotis_yanbarensis", "Myotis_schaubi", "Myotis_escalerai", "Myotis_lavali", "Myotis_pequinius", "Myotis_bombinus", "Myotis_nattereri", "Myotis_chinensis", "Myotis_punicus", "Myotis_insularum", "Myotis_blythii", "Myotis_myotis", "Myotis_csorbai", "Myotis_sicarius", "Myotis_rufopictus", "Myotis_frater", "Myotis_bechsteinii", "Myotis_ater", "Myotis_petax", "Myotis_izecksohni", "Myotis_midastactus", "Myotis_macrodactylus", "Myotis_pilosus", "Myotis_fimbriatus", "Myotis_oreias", "Myotis_daubentonii", "Myotis_hajastanicus", "Myotis_macropus", "Myotis_adversus", "Myotis_hasseltii", "Myotis_occultus", "Myotis_macrotarsus", "Myotis_horsfieldii", "Myotis_rosseti", "Myotis_ridleyi", "Myotis_laniger", "Myotis_hermani", "Myotis_annamiticus", "Myotis_longipes", "Myotis_siligorensis", "Myotis_davidii", "Myotis_phanluongi", "Myotis_dieteri", "Myotis_morrisi", "Myotis_capaccinii", "Myotis_soror", "Myotis_stalkeri", "Myotis_ikonnikovi", "Myotis_altarium", "Myotis_nipalensis", "Myotis_aurascens", "Myotis_handleyi", "Myotis_dasycneme", "Myotis_muricola", "Myotis_scotti", "Myotis_flavus", "Myotis_findleyi", "Myotis_tricolor", "Myotis_emarginatus", "Myotis_goudoti", "Myotis_anjouanensis", "Myotis_bocagii", "Myotis_formosus", "Myotis_welwitschii", "Phoniscus_atrox", "Phoniscus_papuensis", "Phoniscus_aerosa", "Phoniscus_jagorii")

Micro <- c("Miniopterus_inflatus", "Miniopterus_maghrebensis", "Miniopterus_newtoni", "Miniopterus_mossambicus", "Miniopterus_natalensis", "Miniopterus_paululus", "Miniopterus_oceanensis", "Miniopterus_griveaudi", "Miniopterus_minor", "Miniopterus_fraterculus", "Miniopterus_petersoni", "Miniopterus_manavi", "Miniopterus_aelleni", "Miniopterus_majori", "Miniopterus_egeri", "Miniopterus_robustior", "Miniopterus_griffithsi", "Miniopterus_ambohitrensis", "Miniopterus_gleni", "Miniopterus_schreibersii", "Miniopterus_shortridgei", "Miniopterus_brachytragos", "Miniopterus_magnater", "Miniopterus_fuscus", "Miniopterus_fuliginosus", "Miniopterus_sororculus", "Miniopterus_pusillus", "Miniopterus_macrocneme", "Miniopterus_australis", "Miniopterus_medius", "Miniopterus_mahafaliensis", "Miniopterus_tristis")

variable_clade_name <- c("Rhinopomatidae", "Rhinolophidae", "Rhinonycteridae", "Hipposideridae", "Emballonuridae", "Molossidae", "Pteropodidae", "Phyllostomidae", "Vesper", "Micro")

```

Read in the set of trees:

```{r}
library(phytools)
treelist <- read.tree("data/pruned_trees.nex")
```

Loop over the trees, isolating the different clades.
```{r}

  for (x in 1:100){
    treelist[[x]] <- keep.tip(treelist[[x]], Micro)
    x <- x+1
  }
  writeNexus(treelist, file="data/Micro.nex")
```
